import './global.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  // if window width is smaller than 768px, remove the children from the DOM

  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
